version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: aqua-app
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
        depends_on:
            - mysql
        networks: [aqua]

    nginx:
        image: nginx:alpine
        container_name: aqua-nginx
        ports:
            - "80:80"
            # - "443:443"
        volumes:
            - .:/var/www:ro
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro   # <-- единственный конфиг
        depends_on:
            - app
            - reverb
        networks: [ aqua ]

    mysql:
        image: mysql:8.0
        container_name: aqua-mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: aqua
            MYSQL_USER: aqua
            MYSQL_PASSWORD: aqua
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql-data:/var/lib/mysql
        networks: [aqua]

    reverb:
        build:
            context: .
            dockerfile: docker/reverb/Dockerfile
        container_name: aqua-reverb
        environment:
            APP_ENV: production
            REVERB_APP_ID: aqua
            REVERB_APP_KEY: aqua_key
            REVERB_APP_SECRET: aqua_secret
            REVERB_PORT: 6001
        expose:
            - "6001"
        depends_on:
            - app
        networks: [aqua]

volumes:
    mysql-data:

networks:
    aqua:
        driver: bridge
