version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: aqua-app
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - aqua

    nginx:
        image: nginx:alpine
        container_name: aqua-nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - aqua

    mysql:
        image: mysql:8.0
        container_name: aqua-mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: aqua
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - aqua

    reverb:
        build:
            context: .
            dockerfile: docker/reverb/Dockerfile
        container_name: aqua-reverb
        restart: unless-stopped
        ports:
            - "6001:6001"
        environment:
            REVERB_APP_ID: aqua
            REVERB_APP_KEY: aqua_key
            REVERB_APP_SECRET: aqua_secret
            REVERB_PORT: 6001
        networks:
            - aqua

volumes:
    mysql-data:

networks:
    aqua:
        driver: bridge
