services:
    mysql:
        image: mysql:8.0
        container_name: aqua-mysql
        restart: always
        environment:
            MYSQL_DATABASE: aqua
            MYSQL_USER: aqua
            MYSQL_PASSWORD: aqua
            MYSQL_ROOT_PASSWORD: root
            TZ: Europe/Kyiv
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks: [aqua]
        stop_grace_period: 60s
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent"]
            interval: 5s
            timeout: 3s
            retries: 20
            start_period: 20s

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: aqua-app
        restart: always
        environment:
            APP_ENV: production
            APP_DEBUG: "false"
            TZ: Europe/Kyiv
        depends_on:
            mysql:
                condition: service_healthy
        networks: [aqua]
        command: >
            sh -lc "
              php artisan config:cache &&
              php artisan route:cache || true &&
              php artisan migrate --force --no-interaction || true &&
              php-fpm -F
            "

    nginx:
        image: nginx:alpine
        container_name: aqua-nginx
        restart: always
        depends_on:
            app:
                condition: service_started
            reverb:
                condition: service_started
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/cors_map.conf:/etc/nginx/conf.d/cors_map.conf:ro
            - /etc/nginx/ssl:/certs:ro
        networks: [aqua]

    reverb:
        build:
            context: .
            dockerfile: docker/reverb/Dockerfile
        container_name: aqua-reverb
        restart: always
        environment:
            APP_ENV: production
            REVERB_APP_ID: aqua
            REVERB_APP_KEY: aqua_key
            REVERB_APP_SECRET: aqua_secret
            REVERB_PORT: 6001
            TZ: Europe/Kyiv
        expose:
            - "6001"
        depends_on:
            app:
                condition: service_started
        networks: [aqua]

volumes:
    mysql-data:

networks:
    aqua:
        driver: bridge
