version: '3.8'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: aqua-nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: aqua-php
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: production
            APP_KEY: base64:somegeneratedkeyhere
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: aqua
            DB_USERNAME: aqua_user
            DB_PASSWORD: secret
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: aqua-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: aqua
            MYSQL_USER: aqua_user
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
