version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: aqua-taxi-app
        container_name: aqua-taxi-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        working_dir: /var/www/html
        command: php artisan serve --host=0.0.0.0 --port=8000
        networks:
            - aqua-net

    mysql:
        image: mysql:8.2
        container_name: aqua-taxi-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: aqua
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - aqua-net

    vite:
        image: node:18
        container_name: aqua-taxi-vite
        working_dir: /app
        volumes:
            - .:/app
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173"
        networks:
            - aqua-net

volumes:
    db_data:

networks:
    aqua-net:
        driver: bridge
